apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: chatapp
  labels:
    app: backend-chatapp

spec:
  replicas: 1
  selector: 
    matchLabels:
      app: backend-chatapp
  template:
    metadata:
      labels:
        app: backend-chatapp
    spec:
       containers:
       - name: backend-chat-app
         image: vibhutijain12/backend:latest
         ports: 
           - containerPort: 5001
         env: 
           - name: NODE_ENV
             value: production
           - name: MONGODB_URI
             value: "mongodb://mongoadmin:secret@mongodb:27017/dbname?authSource=admin"
           - name: JWT_SECRET
             valueFrom:
               secretKeyRef:
                 name: secret-chatapp
                 key: jwt 
           - name: PORT
             value: "5001"
