apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: chatapp
  labels:
    app: frontend-chatapp

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-chatapp
  template:
    metadata:
      labels:
        app: frontend-chatapp
    spec:
       containers:
       - name: frontend-chat-app
         image: vibhutijain12/frontend:latest
         ports:
           - containerPort: 80
         env:
           - name: NODE_ENV
             value: production
